### PR TITLE
Update rust-training-esp32c3 image

### PR DESCRIPTION
**Pull request by SergioGasquez**
Our training had a big revamp: https://github.com/esp-rs/espressif-trainings/pull/152 and now the Dockerfile from the training [gets published in dockerhub](https://hub.docker.com/r/espressif/rust-std-training). 

I will try to create a project for the exercise and solution for all the projects of the training and link them in the training content.

### CODE REVIEW

**Comment by urish** [comment]
Thanks! A questions + request:

1. Is it possible to switch to non-root user? Running under root increases the attack surface of the builder.
2. Please add all the `HEXI_` environment variables to the Dockerfile (the ones that you used to test the container), similar to what we have here: https://github.com/wokwi/wokwi-builders/blob/27ea6edd25c1198ac6af409ef34f800e90df1c5c/rust-nostd-esp/Dockerfile#L29-L32

**Comment by urish** [comment]
Thanks! What about running the build as non-root user?

**Comment by SergioGasquez** [comment]
> Thanks! What about running the build as non-root user?

I am currently doing some testing on that end, sorry I didn't update you. I started doing test and forgot about updating here.
Will keep you posted!

**Comment by urish** [comment]
Thank you!

**Comment by urish** [comment]
Ready to merge?

**Comment by SergioGasquez** [comment]
> Ready to merge?

Not yet! Give me a moment to do a round of testing!

**Comment by SergioGasquez** [comment]
I think now it should be ready to merge!

**Comment by urish** [comment]
Thanks! Uploading it now, should be up in ~10 minutes or so

**Pull request merged**
