### PR TITLE
Add rust-std-esp builder

### PR DESCRIPTION
**Pull request by SergioGasquez**
- Remove `fetch.sh` for `rust-nostd-esp`
- Add rust-std-esp builder
  - It works for all the targets
  - It allows having the `Cargo.toml` in the project as with no_std
  - I've set [`ESP_IDF_TOOLS_INSTALL_DIR`](https://github.com/esp-rs/esp-idf-sys#esp_idf_tools_install_dir-esp_idf_tools_install_dir) to `global`, so esp-idf installation can be reused.
  - I've commented the `cargo audit` step in `compile.sh` because `esp-idf-hal` depends on a `time` version with vulnerability at the moment:
  ```
  Crate:     time
  Version:   0.1.45
  Title:     Potential segfault in the time crate
  Date:      2020-11-18
  ID:        RUSTSEC-2020-0071
  URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
  Severity:  6.2 (medium)
  Solution:  Upgrade to >=0.2.23
  Dependency tree:
  time 0.1.45
  └── chrono 0.4.24
      └── build-time 0.1.2
          └── esp-idf-sys 0.32.1
              ├── esp32 0.1.0
              ├── esp-idf-svc 0.45.0
              │   └── esp32 0.1.0
              └── esp-idf-hal 0.40.1
                  ├── esp32 0.1.0
                  └── esp-idf-svc 0.45.0
  
  error: 1 vulnerability found!
  ```

### CODE REVIEW

**Comment by SergioGasquez** [comment]
I've re-enabled the cargo audit check ignoring the `RUSTSEC-2020-0071` vulnerability and added the assets folder required to build the esp-clock project. The [esp-clock project](https://wokwi.com/projects/362707751987666945) with its own Cargo.toml file took about 50 secs to build for the first time.

**Comment by urish** [comment]
So are we good to merge?

**Comment by SergioGasquez** [comment]
> So are we good to merge?

Yes! :rocket:

**Comment by urish** [comment]
The new build is in production now!

**Pull request merged**
