### PR TITLE
Zig wasm

### PR DESCRIPTION
**Pull request by kassane**
New experiment.

### Changes:

- Replaced clang-12 with zig toolchain v0.10 (llvm based 15.0.3);
- Experimented using zig-wasm (stage2/3 self-hosting)

cc: @urish

### CODE REVIEW

**Comment by kassane** [comment]
**Note:** Initial purpose for this contribution doesn't include adding embedded solutions written in zig like [Microzig](https://github.com/ZigEmbeddedGroup/microzig) (similar embedded hal [rust]) or sample project like [Zig on the Raspberry Pi Pico](https://github.com/ZigEmbeddedGroup/getting-started-pico-zig)

**Comment by urish** [comment]
Very interesting!

What's the motivation behind switching clang-wasm to the zig toolchain?

**Comment by kassane** [comment]
Portability! The key for zig is having all the libc headers:
https://github.com/ziglang/zig/tree/master/lib/libc

Including the zig toolchain might have a blob of his own in wasm.
- https://github.com/ziglang/zig/pull/13560

**Comment by urish** [comment]
Thanks! I'm not sure why portability is important here.

Can you please split the pull request into two:

- One with the clang-wasm changes
- One with the new zig-wasm builder

This will make it easier to test and discuss each one separately

**Comment by kassane** [comment]
@urish, done (splited)

**Comment by urish** [comment]
Thanks! So regarding zig-wasm, is there any way to move "wokwi_chip_ii.zig" into a different directory? Wokwi always clears the src directory before building the project.

**Comment by kassane** [comment]
> Thanks! So regarding zig-wasm, is there any way to move "wokwi_chip_ii.zig" into a different directory? Wokwi always clears the src directory before building the project.

Done!

**Comment by urish** [comment]
Thanks! I'm doing some integration testing. Meanwhile, a few more things:

1. Why is the library file called `wokwi_chip_ii`? what does `ii` stand for?
2. I see that the [pinMode](https://github.com/wokwi/wokwi_chip_ll/blob/2eb96d5abdce596dbd3114f84fd5b2e549bafc1c/src/lib.rs#L98) function is missing (probably because we forgot to add it in the first version of the Rust API wrapper?)

**Comment by urish** [comment]
Ok, after some initial testing, I see that the .wasm file does not export the function table. Wokwi expects a function table to be exported as `__indirect_function_table`, otherwise, it can't invoke any of the user provided callback (such as `pin_change`). For example, in the Rust build, we achieve this using the [`--export-table` linker argument](https://github.com/wokwi/wokwi-builders/blob/b3f1a94f5b0ca70dd281c36ae22e4630662af20c/rust-wasm/project/.cargo/config.toml#L4).

Do you have any idea how to instruct zig to export the function table?

**Comment by kassane** [comment]
> One more thing I found:
> 
>     4. Is it possible to automatically export a function called `__wokwi_api_version_1` that always returns 1? Right now, Wokwi doesn't check it, but in the future, when we make changes to the chip API, Wokwi will use it to know which version of the API the compiled code is targeting. [Here is](https://github.com/wokwi/wokwi_chip_ll/blob/2eb96d5abdce596dbd3114f84fd5b2e549bafc1c/src/lib.rs#L67-L74) how it's done in Rust.

Wow! `cbindgen` interpreted  `__wokwi_api_version_1` function as external instead of export.

**Comment by urish** [comment]
So can you please tell it to add [`--export-table`](https://lld.llvm.org/WebAssembly.html#cmdoption-export-table) to the `wasm-ld` options?

**Comment by kassane** [comment]
> So can you please tell it to add [`--export-table`](https://lld.llvm.org/WebAssembly.html#cmdoption-export-table) to the `wasm-ld` options?

Reference:
- https://github.com/ziglang/zig/issues/2910#issuecomment-1003460278

```bash
zig build --verbose-link
LLD Link... wasm-ld --error-limit=0 --stack-first --export=table -z stack-size=1048576 --no-entry --allow-undefined -o /home/kassane/Documentos/Projetos/wokwi-zb/zig-wasm/project/zig-cache/o/855a4f1f50c7af981e02026194e4268c/chip_zig.wasm /home/kassane/Documentos/Projetos/wokwi-zb/zig-wasm/project/zig-cache/o/855a4f1f50c7af981e02026194e4268c/chip_zig.wasm.o /home/kassane/.cache/zig/o/09929859fca6d3f6d14ba8e9662932fe/libc.a /home/kassane/.cache/zig/o/5e1af799a7414de202076d24c9667a2d/libcompiler_rt.a
``

**Comment by kassane** [comment]
> 1. Why is the library file called `wokwi_chip_ii`? what does `ii` stand for?

I just copied the name from the original library. Do you want me to rename it?

**Comment by urish** [comment]
The last change added `--export=table` and not `--export-table`, which results in an empty wasm binary:

```wat
(module
  (table $table0 1 1 funcref)
  (memory $memory (;0;) (export "memory") 16)
  (global $global0 (mut i32) (i32.const 1048576))
)
```


> I just copied the name from the original library. Do you want me to rename it?

The original name ended with `ll`, which stands for low-level. For Rust, we intend to create an higher level API abstraction in the future (probably called `wokwi_chip_hal` or similar), so most users won't actually use the `wokwi_chip_ll` directly.

**Comment by kassane** [comment]
@urish , done

**Comment by urish** [comment]
Thanks, I'll test it shortly!

By the way, how did you find out about Wokwi? What was the motivation for adding zig support for the custom chips?

**Comment by kassane** [comment]
> Thanks, I'll test it shortly!
> 
> By the way, how did you find out about Wokwi? 

I got to know wokwi through the franzininho community.

>What was the motivation for adding zig support for the custom chips?

Earlier I spoke only about portability, though believe that zig can improve on this by making solutions simpler (Low Level) and more lightweight.
I don't consider it a competitor to rust because it is inspired by rust, but with a C profile.

**Comment by urish** [comment]
Thanks! I did some initial testing, and it seems to work well. I'll merge and deploy the builder to the staging environment, so you can play around and provide feedback too.

From my testing so far, Zig seems very efficient at producing small wasm binaries!

**Comment by urish** [comment]
p.s. good job on creating a tidy container. Usually pull requests require a lot more effort and feedback from my end to get them working well and be easy to maintain in the future. For most pull requests this takes weeks - you did it in under 3 hours!

**Comment by urish** [comment]
Link to a demo project in the staging environment: https://zig.preview.wokwi.com/projects/348776765607379539

I'd love if you created a few more custom chips to test the integration with the new builder. If you need some ideas, there are several examples here: https://link.wokwi.com/custom-chips-alpha (under the Chip examples section)

**Comment by kassane** [comment]
Hi @urish

It will be a pleasure to help in my spare time and I have even been doing some documentation testing of the zig wrapper.

doc src [sample]:  [zig-doc_wokwi_API.tar.gz](https://github.com/wokwi/wokwi-builders/files/10049802/zig-doc_wokwi_API.tar.gz)

**Preview:**
zig_wokwi_doc

## How to generate doc?

### Single-file

```bash
$> zig build-{lib,exe,obj} mylib.zig -femit-docs
```
### Project 

* open `build.zig`
* add `lib.emit_docs = .{ .emit_to = "custom/path" };` or `lib.emit_docs = .default;`


### Reference

- [Zig Documentation - doc comments](https://ziglang.org/documentation/0.10.0/#Doc-comments)

**Comment by urish** [comment]
Thanks! As far as I understand it, Zig does not have a standard library manager yet, so the only way to have documentation is to self-host it?

**Comment by kassane** [comment]
Exactly.

**Pull request merged**
