### PR TITLE
Make Zephyr build container much faster

### PR DESCRIPTION
**Pull request by beriberikix**
The previous container was building the entire container from scratch. Instead, the new builder is using a pre-built, optimized container from https://github.com/beriberikix/zephyr-docker.

### CODE REVIEW

**Comment by urish** [comment]
Amazing Amazing!

**Comment by urish** [comment]
Deployed the new container and updated the Blinky example to work with the new container (had to replace the includes):

https://wokwi.com/projects/325751453458104914

This is now live!

**Comment by beriberikix** [comment]
Ha, you're fast! This was still in draft. I needed some help to only download the Espressif HAL. With the help of @hasheddan, we were able to [strip it further](https://github.com/beriberikix/wokwi-builders-zephyr/commit/b9d23eb9bc2f02d7e943c376c1889f518bb0375d), making it build a fair bit faster still. We changed a few paths around so it might need be tested against Wokwi again in case the paths break. Should I open another PR?

**Comment by urish** [comment]
Thanks for doing that! Yeah, I wondered why you marked it as draft, as it looked ready to me. Sorry about not asking first before merging it.

Another PR - Yes please.

**Pull request merged**
