### PR TITLE
Use GH releases for installing extra crates

### PR DESCRIPTION
**Pull request by SergioGasquez**

### CODE REVIEW

**Comment by urish** [comment]
Thanks!

Unfortunately, this seems to fail:

```
0.612 /home/esp/.cargo/bin/cargo-audit: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

maybe some os package is missing?

* nostd: https://github.com/wokwi/wokwi-builders/actions/runs/5646146872/job/15293413913
* std: https://github.com/wokwi/wokwi-builders/actions/runs/5646146872/job/15293414334

**Comment by urish** [comment]
Ah, std passes because we're not running `cargo audit` there (in compile.sh)! 

So while at it, can you also add cargo audit to std?

**Comment by SergioGasquez** [comment]
> Interestingly, std passes but nostd fails

That's weird, both use the same base image (`espressif/idf-rust:all_1.71.0.1`) with the same OS packages

**Comment by SergioGasquez** [comment]
> Ah, std passes because we're not running `cargo audit` there (in compile.sh)!
> 
> So while at it, can you also add cargo audit to std?

Ah great, will fix that!

**Pull request merged**
