### PR TITLE
Run cargo-audit for std

### PR DESCRIPTION
**Pull request by SergioGasquez**
In order to fix #47 I created https://github.com/esp-rs/rust-build/pull/227 where I added `openssl` as a dependency.

### CODE REVIEW

**Comment by urish** [comment]
Thanks! This is still failing, unfortunately, with the same error:

https://github.com/wokwi/wokwi-builders/actions/runs/5653970791/job/15316096073

**Comment by SergioGasquez** [comment]
> Thanks! This is still failing, unfortunately, with the same error:
> 
> https://github.com/wokwi/wokwi-builders/actions/runs/5653970791/job/15316096073

Interesting, and it stills succeeds for `std`even though we are running `cargo-audit` like in `no_std`

**Comment by urish** [comment]
Right, because in `std` we commented out the calls to `compile.sh`. I will update the GitHub action to manually the compilation after creating the container, so we can still catch issues

**Comment by urish** [comment]
Okay, I added some code to test the rust-std-esp in the GitHub action, so we can now see when it fails:

https://github.com/wokwi/wokwi-builders/actions/runs/5654206087/job/15316806495

**Pull request merged**
