### PR TITLE
Create esp-rust-std and esp-rust-nostd

### PR DESCRIPTION
**Pull request by SergioGasquez**
Instead of having one builder per target/approach, we can use only two builders, one per approach. 
- Also allows creating a `Cargo.toml` file in the project to share the dependencies.
- Add sccache support
Some build times:
- STD - ESP32C3:
    - Template project build:  ~25 secs
    - Change to `println`: ~ 3 secs
    - Add cached dep and modify code: ~5 secs
    - Add new dep (`esp-idf-hal`) and modify code to import a few stuff from it: ~50 secs
- NO-STD - ESP32:
    - Template project build: I first got an `Unkown build error`, added a comment in the code, rebuilt and took ~10 secs to build successfully.
    - Add cache dep (`esp-println`) and print something: almost instant
    - Add new dep (`pc_keyboard`) and modify code to import a few stuff from it: almost instant

Some notes that are relevant:
- I went for 2 builders instead of one that works for `std` and for `no_std`, as `std` projects are a bit more complex and have files like `build.rs`, sdkcondig.defaults, and a bunch of arguments more in the .cargo/confgi file.  
- Redis URL gets picked from the `REDIST_URL` environment variable
- MCU gets picked from the `WOKWI_MCU` environment variable
-  The `name` of the package in the `Cargo.toml` file must be `"rust-project"`:
```toml
[package]
name = "rust-project"
```

### CODE REVIEW

**Comment by urish** [comment]
Thanks! 

After some quick testing, we need some more changes:

1. Pass `--target` to the rust compiler, based on the selected WOKWI_MCU. E.g. for std esp32, we need `--target xtensa-esp32-espidf`, for std esp32 c3 we need `--target riscv32imc-esp-espidf`.
2. The cache does speed things up - unfortunately, `esp-idf-sys` doesn't seem to be cache, and building it takes a very long time. Is there any way we could improve this?

**Comment by SergioGasquez** [comment]
> 1. Pass `--target` to the rust compiler, based on the selected WOKWI_MCU. E.g. for std esp32, we need `--target xtensa-esp32-espidf`, for std esp32 c3 we need `--target riscv32imc-esp-espidf`.

Why do we need to pass the `--target` argument? When using the template repos, its already handled in the `.cargo/config.toml`:
- [esp-template (`no_std`)](https://github.com/esp-rs/esp-template/blob/main/.cargo/config.toml)
- [esp-idf-template (`std`)](https://github.com/esp-rs/esp-idf-template/blob/master/cargo/.cargo/config.toml)

> 2. The cache does speed things up - unfortunately, `esp-idf-sys` doesn't seem to be cache, and building it takes a very long time. Is there any way we could improve this?
`esp-idf-sys` is the crate that takes care of all the `esp-idf` stuff. Maybe we could try to add [`cargo fetch`](https://doc.rust-lang.org/cargo/commands/cargo-fetch.html) or the building of the project to the `fetch.sh` file.

**Comment by urish** [comment]
> Why do we need to pass the --target argument? When using the template repos, its already handled in the .cargo/config.toml:

The template instantiation happens when you build the container. The chip you are compiling for, `WOKWI_MCU`, is only available at runtime. I see two ways to go about this:
1. Create a different directory for each MCU, using the template mechanism. The build script (`compile.sh`) will look at `WOKWI_MCU` and use it to decide which directory to work with.
2. Create a single directory from the template, and then the build script (`compile.sh`) will pass different parameters to the compiler, based on `WOKWI_MCU`.

> esp-idf-sys is the crate that takes care of all the esp-idf stuff. Maybe we could try to add [cargo fetch](https://doc.rust-lang.org/cargo/commands/cargo-fetch.html) or the building of the project to the fetch.sh file

This is what we are doing today. But now it's getting more complicated: people can specify different version of the esp-idf-sys is their Cargo.toml. Every time someone is doing that, they'll have a very long (around one minute) build time. Over time, there'll be many projects on Wokwi, each with different esp-idf-sys version, and all std project will take a minute or more to build. So we'll need to find a way to cache the result of esp-idf-sys.

**Comment by SergioGasquez** [comment]
> The template instantiation happens when you build the container. The chip you are compiling for, `WOKWI_MCU`, is only available at runtime. I see two ways to go about this:
> 
> 1. Create a different directory for each MCU, using the template mechanism. The build script (`compile.sh`) will look at `WOKWI_MCU` and use it to decide which directory to work with.
> 2. Create a single directory from the template, and then the build script (`compile.sh`) will pass different parameters to the compiler, based on `WOKWI_MCU`.

[8def366](https://github.com/wokwi/wokwi-builders/pull/20/commits/8def3662e35d04fde37670fcaa4e2b1ac3ed0965) implements the later. 


> This is what we are doing today. But now it's getting more complicated: people can specify different version of the esp-idf-sys is their Cargo.toml. Every time someone is doing that, they'll have a very long (around one minute) build time. Over time, there'll be many projects on Wokwi, each with different esp-idf-sys version, and all std project will take a minute or more to build. So we'll need to find a way to cache the result of esp-idf-sys.

We could try using an image with no esp-idf installed, and let [`esp-idf-sys`](https://github.com/esp-rs/esp-idf-sys) install it. We should use [`$ESP_IDF_TOOLS_INSTALL_DIR=global`
](https://github.com/esp-rs/esp-idf-sys#esp_idf_tools_install_dir-esp_idf_tools_install_dir) to reuse installations. But still, the first time a new esp-idf version is used, the build time will be quite slow

**Comment by urish** [comment]
> We could try using an image with no esp-idf installed, and let [esp-idf-sys](https://github.com/esp-rs/esp-idf-sys) install it. We should use [$ESP_IDF_TOOLS_INSTALL_DIR=global](https://github.com/esp-rs/esp-idf-sys#esp_idf_tools_install_dir-esp_idf_tools_install_dir)

Where are the versions installed? How much time does the first-time installation take?

The thing is that many users will hit the "first time" scenario, because containers are created and destroyed on demand.

**Comment by SergioGasquez** [comment]
> Where are the versions installed? How much time does the first-time installation take?

Using `global`installs esp-idf under `~/.espressif`. Regarding the time, it may take 3 or 4 minutes...

> The thing is that many users will hit the "first time" scenario, because containers are created and destroyed on demand.

At the moment, in Wokwi, you can only use one version of esp-idf (`release/v4.4`). As this is defined in `.cargo/config.toml` and the use is not able to edit it. 

Maybe our current approach is better, but we will need to investigate if we can speed up the first build by looking into `esp-idf-sys` but I don't know if there is anything that we can do.

**Comment by urish** [comment]
How about we get the nostd in first and then try to figure this out?

**Comment by SergioGasquez** [comment]
> How about we get the nostd in first and then try to figure this out?

Good idea! Just updated the repo and deleted the `std`

**Pull request closed without merging**
